language: swift

osx_image: xcode10.2

script:
  - xcodebuild test -enableCodeCoverage YES -scheme HPGradientLoading -workspace HPGradientLoading.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=12.2'

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -t 1f66f9e6-a679-490d-9a8f-72dcdbb89daf -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
